# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Swift 5.9.0
      run: |
        curl -O https://download.swift.org/swift-5.10-release/xcode/swift-5.10-RELEASE/swift-5.10-RELEASE-osx.pkg
        sudo installer -pkg swift-5.10-RELEASE-osx.pkg -target /

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
